account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/', views.user_profile, name='user_profile'),
]

administrator/urls.py
from django.urls import path
from . import views

app_name = 'administrator'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
            views.post_detail,
            name='post_detail'),
    path('share/<int:post_id>/', views.post_share, name='post_share'),
]

lms/urls.py
from django.urls import path
from . import views

app_name = 'lms'

urlpatterns = [
    path('', views.index, name='index'),
    path('term/list/', views.term_list, name='term_list'),
    path('term/new/', views.term_new, name='term_new'),
    path('term/edit/<int:pk>/', views.term_edit, name='term_edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrator/', include('administrator.urls', namespace='administrator')),
    path('account/', include('account.urls', namespace='account')),
    path('lms/', include('lms.urls', namespace='lms')),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='p')

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'انتشار یافته')
    )
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, unique_for_date='publish')
    author = models.ForeignKey(User,
            on_delete=models.CASCADE,
            related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                args=[self.publish.year,
                    self.publish.month,
                    self.publish.day,
                    self.slug])

    # Return fullname of post author
    def get_author(self):
        return f"{self.author.first_name} {self.author.last_name}"

blog/forms.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)
    

administrator/views.py
from django.shortcuts import render

def dashboard(request):
    return render(request, 'administrator/apps/dashboard.html')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.views.generic import ListView
from .models import Post
from .forms import EmailPostForm

def post_list(request):
    posts = Post.published.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/post/list.html', context)

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
            status = 'p',
            publish__year=year,
            publish__month=month,
            publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})

def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                    f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'lord.smrha@gmail.com', cd['to'])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'form': form,
        'post': post,
        'sent': sent
    }
    return render(request, 'blog/post/share.html', context)

blog/templates/administrator/base.html
{% load static %}
<!DOCTYPE html>
<html class="loading" lang="fa" data-textdirection="rtl" dir="rtl">
  <!-- BEGIN: Head-->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>قالب پنل مدیریت Frest</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'admin/assets/images/ico/favicon.ico' %}">
	  <meta name="theme-color" content="#5A8DEE">
    
    {% include "administrator/style.html" %}

    {% block style %}{% endblock %}

  </head>
  <!-- END: Head-->

  <!-- BEGIN: Body-->
  <body class="vertical-layout vertical-menu-modern dark-layout 2-columns  navbar-sticky footer-static  " data-open="click" data-menu="vertical-menu-modern" data-col="2-columns" data-layout="dark-layout">

    {% include "administrator/navbar.html" %}

    {% include "administrator/sidebar.html" %}

    {% block content %}

    {% endblock %}

    {% include "administrator/footer.html" %}

    {% include "administrator/script.html" %}

    {% block script %}{% endblock %}

  </body>
  <!-- END: Body-->
</html>

blog/templates/administrator/footer.html
{% load static %}
<div class="sidenav-overlay"></div>
<div class="drag-target"></div>
<!-- BEGIN: Footer-->
<footer class="footer footer-static footer-dark">
  <p class="clearfix mb-0">
    <span class="float-left d-inline-block"
      >ارائه شده در وب‌سایت
      <a href="https://www.rtl-theme.com" target="_blank">راست‌چین</a></span
    ><span class="float-right d-sm-inline-block d-none"
      >ساخته شده با<i class="bx bxs-heart pink ml-50 font-small-3"></i
    ></span>
    <button class="btn btn-primary btn-icon scroll-top" type="button">
      <i class="bx bx-up-arrow-alt"></i>
    </button>
  </p>
</footer>
<!-- END: Footer-->

blog/templates/administrator/login-base.html
{% load static %}
<!DOCTYPE html>
<html class="loading" lang="fa" data-textdirection="rtl" dir="rtl">
  <!-- BEGIN: Head-->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>صفحه ورود</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'admin/assets/images/ico/favicon.ico' %}">
	<meta name="theme-color" content="#5A8DEE">
    
    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'admin/assets/vendors/css/vendors.min.css' %}">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/bootstrap-extended.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/colors.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/components.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/themes/dark-layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/themes/semi-dark-layout.css' %}">
    <!-- END: Theme CSS-->

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/core/menu/menu-types/vertical-menu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/pages/authentication.css' %}">
    <!-- END: Page CSS-->

  </head>
  <!-- END: Head-->

  <!-- BEGIN: Body-->
  <body class="vertical-layout vertical-menu-modern dark-layout 1-column  navbar-sticky footer-static bg-full-screen-image  blank-page blank-page" data-open="click" data-menu="vertical-menu-modern" data-col="1-column" data-layout="dark-layout">
    <!-- BEGIN: Content-->
    <div class="app-content content">
      <div class="content-overlay"></div>
      <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="content-body">
            {% block body %}

            {% endblock %}
        </div>
      </div>
    </div>
    <!-- END: Content-->


    <!-- BEGIN: Vendor JS-->
    <script src="{% static 'admin/assets/vendors/js/vendors.min.js' %}"></script>
    <script src="{% static 'admin/assets/fonts/LivIconsEvo/js/LivIconsEvo.tools.min.js' %}"></script>
    <script src="{% static 'admin/assets/fonts/LivIconsEvo/js/LivIconsEvo.defaults.js' %}"></script>
    <script src="{% static 'admin/assets/fonts/LivIconsEvo/js/LivIconsEvo.min.js' %}"></script>
    <!-- BEGIN Vendor JS-->

    <!-- BEGIN: Page Vendor JS-->
    <!-- END: Page Vendor JS-->

    <!-- BEGIN: Theme JS-->
    <script src="{% static 'admin/assets/js/scripts/configs/vertical-menu-dark.js' %}"></script>
    <script src="{% static 'admin/assets/js/core/app-menu.js' %}"></script>
    <script src="{% static 'admin/assets/js/core/app.js' %}"></script>
    <script src="{% static 'admin/assets/js/scripts/components.js' %}"></script>
    <script src="{% static 'admin/assets/js/scripts/footer.js' %}"></script>
    <!-- END: Theme JS-->

    <!-- BEGIN: Page JS-->
    <!-- END: Page JS-->

  </body>
  <!-- END: Body-->
</html>

blog/templates/administrator/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | {% block title %}{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'admin/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'admin/dist/css/adminlte.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- Custom style for RTL -->
  <link rel="stylesheet" href="{% static 'admin/dist/css/custom.css' %}" />
</head>
<body class="hold-transition login-page">

{% block content %}

{% endblock %}

<!-- jQuery -->
<script src="{% static 'admin/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'admin/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

blog/templates/administrator/navbar.html
{% load static %}
<!-- BEGIN: Header-->
<div class="header-navbar-shadow"></div>
<nav class="header-navbar main-header-navbar navbar-expand-lg navbar navbar-with-menu fixed-top navbar-dark">
  <div class="navbar-wrapper">
    <div class="navbar-container content">
      <div class="navbar-collapse" id="navbar-mobile">
        <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
          <ul class="nav navbar-nav">
            <li class="nav-item mobile-menu d-xl-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ficon bx bx-menu"></i></a></li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="nav-item d-none d-lg-block"><a class="nav-link bookmark-star"><i class="ficon bx bx-star warning"></i></a>
              <div class="bookmark-input search-input">
                <div class="bookmark-input-icon"><i class="bx bx-search primary"></i></div>
                <input class="form-control input" type="text" placeholder="جستجو ..." tabindex="0" data-search="template-search">
                <ul class="search-list"></ul>
              </div>
            </li>
          </ul>
        </div>
        <ul class="nav navbar-nav float-right">
          <li class="dropdown dropdown-user nav-item">
            <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
              <div class="user-nav d-sm-flex d-none">
                <span class="user-name">تونی استارک</span>
                <span class="user-status text-muted">آماده</span>
              </div>
              <span><img class="round" src="{% static 'admin/assets/images/portrait/small/avatar-s-11.jpg' %}" alt="avatar" height="40" width="40"></span>
            </a>
            <div class="dropdown-menu pb-0">
              <a class="dropdown-item" href="{% url 'account:user_profile' %}"><i class="bx bx-user mr-50"></i>حساب کاربری</a>
              <div class="dropdown-divider mb-0"></div>
              <a class="dropdown-item" href="{% url 'account:user_logout' %}"><i class="bx bx-power-off mr-50"></i> خروج</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>
<!-- END: Header-->

blog/templates/administrator/script.html
{% load static %}
<!-- BEGIN: Vendor JS-->
<script src="{% static 'admin/assets/js/scripts/jquery/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'admin/assets/js/scripts/popper/popper.min.js' %}"></script>
<script src="{% static 'admin/assets/vendors/js/vendors.min.js' %}"></script>
<script src="{% static 'admin/assets/fonts/LivIconsEvo/js/LivIconsEvo.tools.min.js' %}"></script>
<script src="{% static 'admin/assets/fonts/LivIconsEvo/js/LivIconsEvo.defaults.js' %}"></script>
<script src="{% static 'admin/assets/fonts/LivIconsEvo/js/LivIconsEvo.min.js' %}"></script>
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="{% static 'admin/assets/vendors/js/charts/apexcharts.min.js' %}"></script>
<script src="{% static 'admin/assets/vendors/js/extensions/dragula.min.js' %}"></script>
<!-- END: Page Vendor JS-->

<!-- BEGIN: Theme JS-->
<script src="{% static 'admin/assets/js/scripts/configs/vertical-menu-dark.js' %}"></script>
<script src="{% static 'admin/assets/js/core/app-menu.js' %}"></script>
<script src="{% static 'admin/assets/js/core/app.js' %}"></script>
<script src="{% static 'admin/assets/js/scripts/components.js' %}"></script>
<script src="{% static 'admin/assets/js/scripts/footer.js' %}"></script>
<script src="{% static 'admin/assets/js/scripts/customizer.js' %}"></script>
<!-- END: Theme JS-->

blog/templates/administrator/sidebar.html
{% load static %}
<!-- BEGIN: Main Menu-->
<div class="main-menu menu-fixed menu-dark menu-accordion menu-shadow" data-scroll-to-active="true">
  <div class="navbar-header">
    <ul class="nav navbar-nav flex-row">
      <li class="nav-item mr-auto"><a class="navbar-brand" href="{% static 'admin/html/vertical-menu-template-dark/index.html' %}">
          <div class="brand-logo"><img class="logo" src="{% static 'admin/assets/images/logo/logo.png' %}"></div>
          <h2 class="brand-text mb-0">Frest</h2></a></li>
      <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i class="bx bx-x d-block d-xl-none font-medium-4 primary"></i><i class="toggle-icon bx bx-disc font-medium-4 d-none d-xl-block primary" data-ticon="bx-disc"></i></a></li>
    </ul>
  </div>
  <div class="shadow-bottom"></div>
  <div class="main-menu-content">
    <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation" data-icon-style="lines">
      <li class=" navigation-header"><span>برنامه ها</span>
      </li>
      <li class=" nav-item"><a href="app-email.html"><i class="menu-livicon" data-icon="envelope-pull"></i><span class="menu-title" data-i18n="Email">ایمیل</span></a>
      </li>
      <li class=" nav-item"><a href="#"><i class="menu-livicon" data-icon="notebook"></i><span class="menu-title" data-i18n="Invoice">صورتحساب</span></a>
        <ul class="menu-content">
          <li><a href="app-invoice-list.html"><i class="bx bx-left-arrow-alt"></i><span class="menu-item" data-i18n="Invoice List">لیست صورتحساب ها</span></a>
          </li>
          <li><a href="app-invoice.html"><i class="bx bx-left-arrow-alt"></i><span class="menu-item" data-i18n="Invoice">صورتحساب</span></a>
          </li>
        </ul>
      </li>
      <li class=" navigation-header"><span>تنظیمات</span>
      </li>
      <li class=" nav-item"><a href="#"><i class="menu-livicon" data-icon="notebook"></i><span class="menu-title" data-i18n="Invoice">حساب کاربری</span></a>
        <ul class="menu-content">
          <li><a href="{% url 'account:user_profile' %}"><i class="bx bx-left-arrow-alt"></i><span class="menu-item">حساب کاربری</span></a>
          </li>
        </ul>
      </li>    
    </ul>
  </div>
</div>
<!-- END: Main Menu-->

blog/templates/administrator/style.html
{% load static %}
<!-- BEGIN: Vendor CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/vendors/css/vendors.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/vendors/css/charts/apexcharts.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/vendors/css/extensions/dragula.min.css' %}">
<!-- END: Vendor CSS-->

<!-- BEGIN: Theme CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/bootstrap-extended.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/colors.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/components.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/themes/dark-layout.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/themes/semi-dark-layout.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/plugins/PersianDatepicker/jquery.md.bootstrap.datetimepicker.style.css' %}">
<!-- END: Theme CSS-->