account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/', views.user_profile, name='user_profile'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
            views.post_detail,
            name='post_detail'),
    path('share/<int:post_id>/', views.post_share, name='post_share'),
]

lms/urls.py
from django.urls import path
from . import views

app_name = 'lms'

urlpatterns = [
    path('', views.index, name='index'),
    path('term/list/', views.term_list, name='term_list'),
    path('term/new/', views.term_new, name='term_new'),
    path('term/edit/<int:pk>/', views.term_edit, name='term_edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrator/', include('administrator.urls', namespace='administrator')),
    path('account/', include('account.urls', namespace='account')),
    path('lms/', include('lms.urls', namespace='lms')),
    path('blog/', include('blog.urls', namespace='blog'))
]

account/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=11, blank=True)
    address = models.CharField(max_length=255, blank=True)
    birthday = models.DateField(default=now, blank=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='p')

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'انتشار یافته')
    )
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, unique_for_date='publish')
    author = models.ForeignKey(User,
            on_delete=models.CASCADE,
            related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                args=[self.publish.year,
                    self.publish.month,
                    self.publish.day,
                    self.slug])

    # Return fullname of post author
    def get_author(self):
        return f"{self.author.first_name} {self.author.last_name}"

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserLoginForm(forms.Form):
    username = forms.CharField(
        label = 'نام کاربری',
        widget = forms.TextInput(attrs = {
            'class': 'form-control'
        }))

    password = forms.CharField(
        label = 'رمز عبور',
        widget = forms.PasswordInput(attrs = {
            'class': 'form-control'
        }))

class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(
        label ='نام',
        widget = forms.TextInput(attrs = {
            'class': 'form-control',
            'placeholder': ''
        }))

    last_name = forms.CharField(
        label ='نام خانوادگی',
        widget = forms.TextInput(attrs = {
            'class': 'form-control',
            'placeholder': ''
        }))

    email = forms.EmailField(
        label ='ایمیل',
        widget = forms.TextInput(attrs = {
            'class': 'form-control',
            'placeholder': ''
        }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class ProfileEditForm(forms.ModelForm):
    mobile = forms.CharField(
        label ='تلفن همراه',
        widget = forms.TextInput(attrs = {
            'class': 'form-control',
            'placeholder': ''
        }))

    address = forms.CharField(
        label ='آدرس',
        widget = forms.TextInput(attrs = {
            'class': 'form-control',
            'placeholder': ''
        }))

    birthday = forms.DateField(
        label ='تاریخ تولد',
        widget = forms.DateInput(attrs = {
            'class': 'form-control',
            'type': 'hidden',
            'placeholder': ''
        }))

    class Meta:
        model = Profile
        fields = ['mobile', 'address', 'birthday']

blog/forms.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)
    

account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import UserEditForm, ProfileEditForm, UserLoginForm
from django.contrib.auth import authenticate, login, logout

# Login user to the site
def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                    username=cd['username'],
                    password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('administrator:dashboard')
                else:
                    messages.error(request, "کاربر غیر فعال می باشد.", "text-error")
            else:
                messages.error(request, "نام کاربری و یا رمز عبور اشتباه می باشد.", "text-danger")
    else:
        form = UserLoginForm()
    context = {
        'form': form
    }
    return render(request, 'administrator/apps/account/user-login.html', context)

# Logout from the site

def user_logout(request):
    logout(request)
    return redirect('account:user_login')

# Edit and show user profile information
@login_required
def user_profile(request):
    if request.method == "POST":
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = ProfileEditForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('account:user_profile')
        else:
            print("Invalid")
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }
    return render(request, 'administrator/apps/account/user-profile.html', context)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.views.generic import ListView
from .models import Post
from .forms import EmailPostForm

def post_list(request):
    posts = Post.published.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/post/list.html', context)

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
            status = 'p',
            publish__year=year,
            publish__month=month,
            publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})

def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                    f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'lord.smrha@gmail.com', cd['to'])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'form': form,
        'post': post,
        'sent': sent
    }
    return render(request, 'blog/post/share.html', context)

blog/templates/administrator/apps/account/user-login.html
{% extends "administrator/login-base.html" %}
{% load static %}

{% block body %}
<!-- login page start -->
<section id="auth-login" class="row flexbox-container">
    <div class="col-xl-8 col-11">
        <div class="card bg-authentication mb-0">
            <div class="row m-0">
                <!-- left section-login -->
                <div class="col-md-6 col-12 px-0">
                    <div class="card disable-rounded-right mb-0 p-2 h-100 d-flex justify-content-center">
                        <div class="card-header pb-1">
                            <div class="card-title">
                                <h4 class="text-center mb-2">خوش آمدید</h4>
                            </div>
                        </div>
                        <div class="card-content">
                            <div class="card-body">
                                <hr>
                                {% if messages %}
                                <div class="messages">
                                    {% for message in messages %}
                                    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                                    {% endfor %}
                                </div>
                                {% endif %}
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class=" mb-1">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">{{ form.username.label }}</span>
                                            </div>
                                            {{ form.username }}
                                        </div>
                                    </div>
                                    <div class=" mb-1">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">{{ form.password.label }}</span>
                                            </div>
                                            {{ form.password }}
                                        </div>
                                    </div>
                                    <div class="form-group d-flex flex-md-row flex-column justify-content-between align-items-center">
                                        <div class="text-left">
                                            <div class="checkbox checkbox-sm">
                                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                                <label class="checkboxsmall" for="exampleCheck1"><small>مرا به خاطر بسپار</small></label>
                                            </div>
                                        </div>
                                        <div class="text-right line-height-2"><a href="auth-forgot-password.html" class="card-link"><small>رمز عبورتان را فراموش کرده اید؟</small></a></div>
                                    </div>
                                    <button type="submit" class="btn btn-primary glow w-100 position-relative">ورود<i id="icon-arrow" class="bx bx-left-arrow-alt"></i></button>
                                </form>
                                <hr>
                                <div class="text-center"><small class="mr-25">حسابی ندارید؟</small><a href="auth-register.html"><small>ثبت نام</small></a></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- right section image -->
                <div class="col-md-6 d-md-block d-none text-center align-self-center p-3">
                    <div class="card-content">
                        <img class="img-fluid" src="{% static 'admin/assets/images/pages/login.png' %}" alt="branding logo">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- login page ends -->
{% endblock %}

blog/templates/administrator/apps/account/user-profile.html
{% extends "administrator/base.html" %}
{% load static %}

{% block style %}
<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/core/menu/menu-types/vertical-menu.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/pages/page-user-profile.css' %}">
<!-- END: Page CSS-->
{% endblock %}

{% block content %}
<!-- BEGIN: Content-->
<div class="app-content content">
  <div class="content-overlay"></div>
  <div class="content-wrapper">
    <div class="content-header row">
    </div>
    <div class="content-body">
      <!-- page user profile start -->
      <section class="page-user-profile">
        <div class="row">
          <div class="col-12">
            <!-- user profile heading section start -->
            <div class="card">
              <div class="card-content">
                <div class="user-profile-images">
                  <!-- user timeline image -->
                  <img src="{% static 'admin/assets/images/profile/post-media/profile-banner.jpg' %}" class="img-fluid rounded-top user-timeline-image" alt="user timeline image">
                  <!-- user profile image -->
                  <img src="{% static 'admin/assets/images/portrait/small/avatar-s-16.jpg' %}" class="user-profile-image rounded" alt="user profile image" height="140" width="140">
                </div>
                <div class="user-profile-text">
                  <h4 class="mb-0 text-bold-500 profile-text-color">{{ user.first_name }} {{ user.last_name }}</h4>
                  <small>توسعه دهنده</small>
                </div>
                <!-- user profile nav tabs start -->
                <div class="card-body px-0">
                  <ul class="nav user-profile-nav justify-content-center justify-content-md-start nav-tabs border-bottom-0 mb-0" role="tablist">
                    <li class="nav-item pb-0">
                      <a class="nav-link d-flex px-1 active align-items-center" id="feed-tab" data-toggle="tab" href="#feed" aria-controls="feed" role="tab" aria-selected="true"><i class="bx bx-home"></i><span class="d-none d-md-block">خوراک</span></a>
                    </li>
                    <li class="nav-item pb-0">
                      <a class="nav-link d-flex px-1 align-items-center" id="activity-tab" data-toggle="tab" href="#activity" aria-controls="activity" role="tab" aria-selected="false"><i class="bx bx-user"></i><span class="d-none d-md-block">فعالیت</span></a>
                    </li>
                    <li class="nav-item pb-0">
                      <a class="nav-link d-flex px-1 align-items-center" id="friends-tab" data-toggle="tab" href="#friends" aria-controls="friends" role="tab" aria-selected="false"><i class="bx bx-message-alt"></i><span class="d-none d-md-block">دوستان</span></a>
                    </li>
                    <li class="nav-item pb-0 mr-0">
                      <a class="nav-link d-flex px-1 align-items-center" id="profile-tab" data-toggle="tab" href="#profile" aria-controls="profile" role="tab" aria-selected="false"><i class="bx bx-copy-alt"></i><span class="d-none d-md-block">پروفایل</span></a>
                    </li>
                  </ul>
                </div>
                <!-- user profile nav tabs ends -->
              </div>
            </div>
            
            <!-- user profile nav tabs profile start -->
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">اطلاعات کاربر</h4>
              </div>
              <div class="card-content">
                
                <div class="card-body">
                  <form class="form form-horizontal" method="POST">
                    {% csrf_token %}
                    <div class="form-body">
                      </br>

                      <div class="row">
                        <div class="col-lg-4 mb-1">
                            <div class="input-group">
                              <div class="input-group-prepend">
                                <span class="input-group-text">{{ user_form.first_name.label }}</span>
                              </div>
                              {{ user_form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-4 mb-1">
                            <div class="input-group">
                              <div class="input-group-prepend">
                                <span class="input-group-text">{{ user_form.last_name.label }}</span>
                              </div>
                              {{ user_form.last_name }}
                            </div>
                        </div>
                        <div class="col-lg-4 mb-1">
                            <div class="input-group">
                              <div class="input-group-prepend">
                                <span class="input-group-text">{{ user_form.email.label }}</span>
                              </div>
                              {{ user_form.email }}
                            </div>
                        </div>
                        <div class="col-lg-4 mb-1">
                            <div class="input-group">
                              <div class="input-group-prepend">
                                <span class="input-group-text">{{ profile_form.mobile.label }}</span>
                              </div>
                              {{ profile_form.mobile }}
                            </div>
                        </div>
                        <div class="col-lg-4 mb-1">
                            <div class="input-group">
                              <div class="input-group-prepend">
                                <span class="input-group-text">{{ profile_form.birthday.label }}</span>
                              </div>
                              <input type="text" id="input_birthday" class="form-control">
                              {{ profile_form.birthday }}
                            </div>
                        </div>
                        <div class="col-lg-8 mb-1">
                            <div class="input-group">
                              <div class="input-group-prepend">
                                <span class="input-group-text">{{ profile_form.address.label }}</span>
                              </div>
                              {{ profile_form.address }}
                            </div>
                        </div>

                        <div class="col-sm-12 d-flex justify-content-end">
                          <button type="submit" class="btn btn-primary mr-1 mb-1">ثبت</button>
                          <button type="reset" class="btn btn-light-secondary mr-1 mb-1">بازنشانی</button>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <!-- user profile nav tabs profile ends -->
          </div>
        </div>
      </section>
      <!-- page user profile ends -->

    </div>
  </div>
</div>
<!-- END: Content-->

{% endblock %}

{% block script %}
<!-- BEGIN: Page JS-->
<script src="{% static 'admin/assets/js/scripts/pages/page-user-profile.js' %}"></script>
<script src="{% static 'admin/assets/js/scripts/PersianDatepicker/jquery.md.bootstrap.datetimepicker.js' %}"></script>
<script type="text/javascript">
  $("#input_birthday").MdPersianDateTimePicker({
    targetDateSelector: "#id_birthday",
    targetTextSelector: "#input_birthday",
    dateFormat: "yyyy-MM-dd",
    textFormat: " dddd dd MMMM yyyy ",
  });
</script>
<!-- END: Page JS-->
{% endblock %}
    