blog/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
            views.post_detail,
            name='post_detail'),
    path('share/<int:post_id>/', views.post_share, name='post_share'),
]

lms/urls.py
from django.urls import path
from . import views

app_name = 'lms'

urlpatterns = [
    path('', views.index, name='index'),
    path('term/list/', views.term_list, name='term_list'),
    path('term/new/', views.term_new, name='term_new'),
    path('term/edit/<int:pk>/', views.term_edit, name='term_edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrator/', include('administrator.urls', namespace='administrator')),
    path('account/', include('account.urls', namespace='account')),
    path('lms/', include('lms.urls', namespace='lms')),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='p')

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'انتشار یافته')
    )
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, unique_for_date='publish')
    author = models.ForeignKey(User,
            on_delete=models.CASCADE,
            related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                args=[self.publish.year,
                    self.publish.month,
                    self.publish.day,
                    self.slug])

    # Return fullname of post author
    def get_author(self):
        return f"{self.author.first_name} {self.author.last_name}"

blog/forms.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.views.generic import ListView
from .models import Post
from .forms import EmailPostForm

def post_list(request):
    posts = Post.published.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/post/list.html', context)

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
            status = 'p',
            publish__year=year,
            publish__month=month,
            publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})

def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                    f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'lord.smrha@gmail.com', cd['to'])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'form': form,
        'post': post,
        'sent': sent
    }
    return render(request, 'blog/post/share.html', context)

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">

                    <h2 class="section-heading">{{ post.title }}</h2>

                    {{ post.body|linebreaks }}

                    <p>
                        <a href="{% url 'blog:post_share' post.id %}">
                        Share this post
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% block title %}Start Bootstrap Theme{% endblock %} 

{% block content %}
    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          {% for post in posts %}
          <div class="post-preview">
            <a href="{{ post.get_absolute_url }}">
              <h2 class="post-title">
                {{ post.title }}
              </h2>
              <h3 class="post-subtitle">
                {{ post.body|truncatewords:30|linebreaks }}
              </h3>
            </a>
            <p class="post-meta">
              Posted by
              <a href="#">{{ post.get_author }}</a>
              on September 24, 2019
            </p>
          </div>
          <hr />
          {% endfor %}
          <!-- Pager -->
          <div class="clearfix">
            <a class="btn btn-primary float-right" href="#"
              >Older Posts &rarr;</a
            >
          </div>
        </div>
      </div>
    </div>
{% endblock %}

blog/templates/blog/post/share.html
{% block title %}Post Share{% endblock %}

{% block content %}
    <!-- Post Share Content -->
    {% if send %}
        <h2>E-mail successfully send</h2>
        <p>
        "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h2>Share {{ post.title }} by e-mail</h2>
        <form method='POST'>
            {% csrf_token %}
            {{ from.as_p }}
            <input type='submit' value='Send e-mail'>
        </form>
    {% endif %}
    
{% endblock %}