blog/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
            views.post_detail,
            name='post_detail'),
    path('share/<int:post_id>/', views.post_share, name='post_share'),
]

lms/urls.py
from django.urls import path
from . import views

app_name = 'lms'

urlpatterns = [
    path('', views.index, name='index'),
    path('term/list/', views.term_list, name='term_list'),
    path('term/new/', views.term_new, name='term_new'),
    path('term/edit/<int:pk>/', views.term_edit, name='term_edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrator/', include('administrator.urls', namespace='administrator')),
    path('account/', include('account.urls', namespace='account')),
    path('lms/', include('lms.urls', namespace='lms')),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='p')

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'انتشار یافته')
    )
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, unique_for_date='publish')
    author = models.ForeignKey(User,
            on_delete=models.CASCADE,
            related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                args=[self.publish.year,
                    self.publish.month,
                    self.publish.day,
                    self.slug])

    # Return fullname of post author
    def get_author(self):
        return f"{self.author.first_name} {self.author.last_name}"

lms/models.py
from django.db import models
from extentions import utils
class Term(models.Model):
    TERM_STATUS = (
        ('a', 'فعال'),
        ('d', 'غیرفعال')
    )
    name = models.CharField(max_length=64)
    begin_date = models.DateField()
    end_date = models.DateField()
    status = models.CharField(max_length=1, choices=TERM_STATUS, default='d')

    def __str__(self):
        return self.name

    def begin_date_jalali(self):
        return utils.to_jalali(self.begin_date)

    def end_date_jalali(self):
        return utils.to_jalali(self.end_date)

    def term_status(self):
        if self.status == 'a':
            return 'فعال'
        else:
            return 'غیرفعال'

blog/forms.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)
    

lms/forms.py
from django import forms
from .models import Term

class TermNewForm(forms.ModelForm):
    TERM_STATUS = (
        ('a', 'فعال'),
        ('d', 'غیرفعال')
    )

    name = forms.CharField(
        label = 'عنوان ترم',
        widget = forms.TextInput(attrs = {
            'class': 'form-control'
        }))

    begin_date = forms.DateField(
        label ='تاریخ آغاز ترم',
        widget = forms.DateInput(attrs = {
            'class': 'form-control',
            'type': 'hidden',
        }))
    
    end_date = forms.DateField(
        label ='تاریخ پایان ترم',
        widget = forms.DateInput(attrs = {
            'class': 'form-control',
            'type': 'hidden',
        }))

    status = forms.ChoiceField(
        choices = TERM_STATUS,
        label = 'وضعیت',
        widget = forms.Select(attrs = {
            'class': 'form-control'
        }))

    class Meta:
        model = Term
        fields = ['name', 'begin_date', 'end_date', 'status']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.views.generic import ListView
from .models import Post
from .forms import EmailPostForm

def post_list(request):
    posts = Post.published.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/post/list.html', context)

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
            status = 'p',
            publish__year=year,
            publish__month=month,
            publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})

def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                    f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'lord.smrha@gmail.com', cd['to'])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'form': form,
        'post': post,
        'sent': sent
    }
    return render(request, 'blog/post/share.html', context)

lms/views.py
from django.shortcuts import render
from .forms import TermNewForm
from .models import Term

def index(request):
    return render(request, 'lms/index.html')

### TERM MODEL VIEWS ###

# List of all terms
def term_list(request):
    terms = Term.objects.all
    context = {
        'terms': terms
    }
    return render(request, 'lms/term/term-list.html', context)

# Adding a new term
def term_new(request):
    if request.method == 'POST':
        form = TermNewForm(request.POST)
        if form.is_valid():
            print(form.is_valid())
            form.save()
        # todo : else
    else:
        form = TermNewForm() 

    context = {
        'form': form
    }
    return render(request, 'lms/term/term-new.html', context)

# Editing the term
def term_edit(request, pk):
    obj = Term.objects.get(id=pk)
    form = TermNewForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()

    context = {
        'form': form
    }
    return render(request, 'lms/term/term-edit.html', context)

blog/templates/lms/term/term-edit.html
{% extends "administrator/base.html" %}
{% load static %}

{% block style %}
<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/core/menu/menu-types/vertical-menu.css' %}">
<!-- END: Page CSS-->
{% endblock %}

{% block content %}
<!-- BEGIN: Content-->
    <div class="app-content content">
      <div class="content-overlay"></div>
      <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="content-body">
          <!-- content Start -->
          <section>
            <div class="row">
              <div class="col-md-12 col-sm-12">
                <div class="card">
                  <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="card-title">ویرایش ترم</h4>
                    <i class="bx bx-dots-vertical-rounded font-medium-3 cursor-pointer"></i>
                  </div>
                  <div class="card-content">
                    <div class="card-body pb-1">
                      <form class="form form-horizontal" method="POST">
                        {% csrf_token %}
                        <div class="form-body">
                          <div class="row">
                            <div class="col-lg-4 mb-1">
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text">{{ form.name.label }}</span>
                                </div>
                                {{ form.name }}
                              </div>
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-lg-4 mb-1">
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text">{{ form.begin_date.label }}</span>
                                </div>
                                <input type="text" id="input_begin_date" class="form-control">
                                {{ form.begin_date }}
                              </div>
                            </div>
                            <div class="col-lg-4 mb-1">
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text">{{ form.end_date.label }}</span>
                                </div>
                                <input type="text" id="input_end_date" class="form-control">
                                {{ form.end_date }}
                              </div>
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-lg-4 mb-1">
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text">{{ form.status.label }}</span>
                                </div>
                                {{ form.status }}
                              </div>
                            </div>
                          </div>
                          <br>
                          <div class="row">
                            <div class="col-sm-12 d-flex">
                              <button type="submit" class="btn btn-primary mr-1 mb-1">ثبت</button>
                              <button type="reset" class="btn btn-light-secondary mr-1 mb-1">بازنشانی</button>
                            </div>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </section>
          <!-- content end -->

        </div>
      </div>
    </div>
    <!-- END: Content-->
{% endblock %}

{% block script %}
<!-- BEGIN: Page JS-->
<script src="{% static 'admin/assets/js/scripts/PersianDatepicker/jquery.md.bootstrap.datetimepicker.js' %}"></script>
<script type="text/javascript">
  $("#input_begin_date").MdPersianDateTimePicker({
    targetDateSelector: "#id_begin_date",
    targetTextSelector: "#input_begin_date",
    dateFormat: "yyyy-MM-dd",
    textFormat: " dddd dd MMMM yyyy ",
  });
  $("#input_end_date").MdPersianDateTimePicker({
    targetDateSelector: "#id_end_date",
    targetTextSelector: "#input_end_date",
    dateFormat: "yyyy-MM-dd",
    textFormat: " dddd dd MMMM yyyy ",
  });
</script>
<!-- END: Page JS-->
{% endblock %}
    

blog/templates/lms/term/term-list.html
{% extends "administrator/base.html" %}
{% load static %}

{% block style %}
<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/core/menu/menu-types/vertical-menu.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/vendors/css/tables/datatable/datatables.min.css' %}">
<!-- END: Page CSS-->
{% endblock %}

{% block content %}
<!-- BEGIN: Content-->
    <div class="app-content content">
      <div class="content-overlay"></div>
      <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="content-body">
          <!-- content Start -->
          <section>
            <div class="row">
              <div class="col-md-12 col-sm-12">
                <div class="card">
                  <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="card-title">لیست ترم ها</h4>
                    <i class="bx bx-dots-vertical-rounded font-medium-3 cursor-pointer"></i>
                  </div>
                  <div class="card-content">
                    <div class="card-body">
                      <div class="table-responsive">
                        <table class="table zero-configuration">
                          <thead>
                            <tr>
                              <th>ردیف</th>
                              <th>عنوان ترم</th>
                              <th>تاریخ آغاز</th>
                              <th>تاریخ پایان</th>
                              <th>وضعیت</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              {% for term in terms %}
                              <td>{{ term.id }}</td>
                              <td>{{ term.name }}</td>
                              <td>{{ term.begin_date_jalali }}</td>
                              <td>{{ term.end_date_jalali }}</td>
                              <td>{{ term.term_status }}</td>
                              {% endfor %}
                            </tr>
                          </tbody>
                          <tfoot>
                            <tr>
                              <th>ردیف</th>
                              <th>عنوان ترم</th>
                              <th>تاریخ آغاز</th>
                              <th>تاریخ پایان</th>
                              <th>وضعیت</th>
                            </tr>
                          </tfoot>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </section>
          <!-- content end -->

        </div>
      </div>
    </div>
    <!-- END: Content-->
{% endblock %}

{% block script %}
<!-- BEGIN: Page JS-->
<script src="{% static 'admin/assets/vendors/js/tables/datatable/datatables.min.js' %}"></script>
<script src="{% static 'admin/assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'admin/assets/vendors/js/tables/datatable/dataTables.buttons.min.js' %}"></script>

<script src="{% static 'admin/assets/js/scripts/datatables/datatable.js' %}"></script>
<!-- END: Page JS-->
{% endblock %}
    

blog/templates/lms/term/term-new.html
{% extends "administrator/base.html" %}
{% load static %}

{% block style %}
<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/core/menu/menu-types/vertical-menu.css' %}">
<!-- END: Page CSS-->
{% endblock %}

{% block content %}
<!-- BEGIN: Content-->
    <div class="app-content content">
      <div class="content-overlay"></div>
      <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="content-body">
          <!-- content Start -->
          <section>
            <div class="row">
              <div class="col-md-12 col-sm-12">
                <div class="card">
                  <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="card-title">ترم جدید</h4>
                    <i class="bx bx-dots-vertical-rounded font-medium-3 cursor-pointer"></i>
                  </div>
                  <div class="card-content">
                    <div class="card-body pb-1">
                      <form class="form form-horizontal" method="POST">
                        {% csrf_token %}
                        <div class="form-body">
                          <div class="row">
                            <div class="col-lg-4 mb-1">
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text">{{ form.name.label }}</span>
                                </div>
                                {{ form.name }}
                              </div>
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-lg-4 mb-1">
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text">{{ form.begin_date.label }}</span>
                                </div>
                                <input type="text" id="input_begin_date" class="form-control">
                                {{ form.begin_date }}
                              </div>
                            </div>
                            <div class="col-lg-4 mb-1">
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text">{{ form.end_date.label }}</span>
                                </div>
                                <input type="text" id="input_end_date" class="form-control">
                                {{ form.end_date }}
                              </div>
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-lg-4 mb-1">
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text">{{ form.status.label }}</span>
                                </div>
                                {{ form.status }}
                              </div>
                            </div>
                          </div>
                          <br>
                          <div class="row">
                            <div class="col-sm-12 d-flex">
                              <button type="submit" class="btn btn-primary mr-1 mb-1">ثبت</button>
                              <button type="reset" class="btn btn-light-secondary mr-1 mb-1">بازنشانی</button>
                            </div>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </section>
          <!-- content end -->

        </div>
      </div>
    </div>
    <!-- END: Content-->
{% endblock %}

{% block script %}
<!-- BEGIN: Page JS-->
<script src="{% static 'admin/assets/js/scripts/PersianDatepicker/jquery.md.bootstrap.datetimepicker.js' %}"></script>
<script type="text/javascript">
  $("#input_begin_date").MdPersianDateTimePicker({
    targetDateSelector: "#id_begin_date",
    targetTextSelector: "#input_begin_date",
    dateFormat: "yyyy-MM-dd",
    textFormat: " dddd dd MMMM yyyy ",
  });
  $("#input_end_date").MdPersianDateTimePicker({
    targetDateSelector: "#id_end_date",
    targetTextSelector: "#input_end_date",
    dateFormat: "yyyy-MM-dd",
    textFormat: " dddd dd MMMM yyyy ",
  });
</script>
<!-- END: Page JS-->
{% endblock %}
    